# 工作流基础配置
workflow:
  name: "自动化测试工作流"
  description: "用于批量自动化执行测试用例并生成测试报告的工作流"

# 执行超时配置（单位：秒）
execution:
  default_timeout: 60  # 步骤默认超时时间
  pre_command_timeout: 30  # 预处理命令超时时间
  post_command_timeout: 30  # 后置命令超时时间
  sleep_time: 10 # 步骤中的子进程启动后，默认睡眠时间

execute_machine:
  remote_ip: "192.168.0.191" # 127.0.0.1  ubuntu remote: 192.168.137.100 （本地：192.168.137.110/255.255.255.0） harmonyos remote: 192.168.0.6 （本地： 192.168.0.110/255.255.255.0） 
  remote_os: ubuntu #   HarmonyOS 需要单独处理，其他的linux机器，如 ubuntu 统一处理
  remote_user: "root7"
  remote_passwd: "606"  #  ubuntu remote: Mind@123 , 鸿蒙系统需要密码
  hdc_port: "5555" #  仅 HarmonyOS 需要需要配置，是 hdc shell 远程连接鸿蒙设备用的端口

# 测试结果和报告路径配置
reports:
  report_path: "reports"
  screenshot_dir: "reports/screenshots"  # 截图保存目录
  report_file: "reports/test_report.html"

# 测试细则Word文档路径配置
word_documents:
  original_template_file: "merged_document.docx"  # 原始测试用例文档
  result_output_file: "reports/test_report.docx"  # 填充结果后的文档

# 日志配置
logging:
  level: "INFO"  # 日志级别：DEBUG/INFO/WARNING/ERROR
  format: "%(asctime)s - %(levelname)s - %(message)s"  # 日志格式
  log_path: "logs"

# 进程管理配置
process:
  kill_timeout: 5  # 进程终止超时时间（秒）

# 环境变量管理
env:
  DISPLAY: ":1"  # 定义 X 服务器的图形界面的环境变量，有些环境应该配置 ":1"，按实际情况配置
      
script:
  full_process_script: "/home/lijiao/work/TE-Agent/sample/full_process_start.sh"  # 全流程启动脚本  /home/lijiao/work/TE-Agent/sample/full_process_start.sh
  stop_full_process_script: "/home/lijiao/work/TE-Agent/sample/full_process_stop.sh" # 全流程停止脚本 /home/lijiao/work/TE-Agent/sample/full_process_stop.sh

